package gov.nasa.gsfc.seadas.sandbox.toolwindow;

import javax.imageio.ImageIO;
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;

/**
 * Created by IntelliJ IDEA.
 * User: dshea
 * Date: 3/27/12
 * Time: 9:37 AM
 * To change this template use File | Settings | File Templates.
 */
public class JunkForm {
    private JTable table1;
    private JButton button1;
    private JButton button2Button;
    private JPanel myPanel;
    private JComboBox comboBox1;
    private JLabel label1;

    private String[] columnNames = {"First Name",
            "Last Name",
            "Sport",
            "# of Years",
            "Vegetarian"};
    private Object[][] data = {
            {"Kathy", "Smith",
                    "Snowboarding", new Integer(5), new Boolean(false)},
            {"John", "Doe",
                    "Rowing", new Integer(3), new Boolean(true)},
            {"Sue", "Black",
                    "Knitting", new Integer(2), new Boolean(false)},
            {"Jane", "White",
                    "Speed reading", new Integer(20), new Boolean(true)},
            {"Joe", "Brown",
                    "Pool", new Integer(10), new Boolean(false)}
    };

    public JunkForm() {
        $$$setupUI$$$();
        button1.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                System.out.println("Button1 pressed");
            }
        });
        comboBox1.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                System.out.println("comboBox - " + comboBox1.getSelectedItem().toString());
                label1.setText(comboBox1.getSelectedItem().toString());
                System.out.printf("label x=%d, y=%d\n", label1.getWidth(), label1.getHeight());
            }
        });
    }

    private void createUIComponents() {
        table1 = new JTable(data, columnNames);
        label1 = new JLabel("stuff");
        try {
            BufferedImage img = ImageIO.read(new File("/home/dshea/Downloads/SeaDAS_splash.small.png"));
            label1.setIcon(new ImageIcon(img));
        } catch (IOException e) {
        }

        System.out.printf("label x=%d, y=%d\n", label1.getWidth(), label1.getHeight());
        comboBox1 = new ColorPaletteChooser(new File("/home/dshea/.beam/beam-ui/auxdata/color-palettes"));

    }

    public static void main(String[] args) {
        JFrame frame = new JFrame("JunkForm");
        frame.setContentPane(new JunkForm().$$$getRootComponent$$$());
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);
    }


    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        myPanel = new JPanel();
        myPanel.setLayout(new GridBagLayout());
        final JScrollPane scrollPane1 = new JScrollPane();
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.gridwidth = 6;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        myPanel.add(scrollPane1, gbc);
        table1.setFillsViewportHeight(false);
        table1.setShowHorizontalLines(true);
        scrollPane1.setViewportView(table1);
        button1 = new JButton();
        button1.setText("Button 1");
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        myPanel.add(button1, gbc);
        button2Button = new JButton();
        button2Button.setEnabled(true);
        button2Button.setHideActionText(false);
        button2Button.setText("Button 2");
        gbc = new GridBagConstraints();
        gbc.gridx = 5;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        myPanel.add(button2Button, gbc);
        label1.setText("Label");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.WEST;
        myPanel.add(label1, gbc);
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        myPanel.add(panel1, gbc);
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        myPanel.add(comboBox1, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return myPanel;
    }
}
